'use client';

import React, { useState, useEffect } from 'react';
import { ArrowLeft, Copy, Check, ShieldCheck, FileText, Globe, RefreshCw, X, Download, AlertCircle, Shield, BookOpen, Sparkles, Plus } from 'lucide-react';
import { toast } from 'sonner';

export const RobotsTxtBuilder: React.FC<{ onBack: () => void }> = ({ onBack }) => {
    const [rules, setRules] = useState([
        { id: '1', agent: '*', type: 'Allow', path: '/' },
        { id: '2', agent: '*', type: 'Disallow', path: '/admin' },
        { id: '3', agent: '*', type: 'Disallow', path: '/api' },
    ]);
    const [sitemap, setSitemap] = useState('https://example.com/sitemap.xml');
    const [copied, setCopied] = useState(false);

    const addRule = () => {
        setRules([...rules, { id: Date.now().toString(), agent: '*', type: 'Disallow', path: '/' }]);
        toast.success('Yeni kural eklendi');
    };

    const removeRule = (id: string) => {
        setRules(rules.filter(r => r.id !== id));
    };

    const updateRule = (id: string, updates: any) => {
        setRules(rules.map(r => r.id === id ? { ...r, ...updates } : r));
    };

    const generateRobots = () => {
        let content = `# Robots.txt generated by Gravity Utils\n\n`;

        // Group by User-agent
        const agents = [...new Set(rules.map(r => r.agent))];
        agents.forEach(agent => {
            content += `User-agent: ${agent}\n`;
            rules.filter(r => r.agent === agent).forEach(r => {
                content += `${r.type}: ${r.path}\n`;
            });
            content += `\n`;
        });

        if (sitemap) {
            content += `Sitemap: ${sitemap}\n`;
        }

        return content;
    };

    const handleCopy = () => {
        navigator.clipboard.writeText(generateRobots());
        setCopied(true);
        setTimeout(() => setCopied(false), 2000);
        toast.success('Pano kopyalandı');
    };

    const downloadFile = () => {
        const content = generateRobots();
        const blob = new Blob([content], { type: 'text/plain' });
        const url = URL.createObjectURL(blob);
        const link = document.createElement('a');
        link.href = url;
        link.download = 'robots.txt';
        link.click();
        toast.success('Dosya indiriliyor');
    };

    return (
        <div className="max-w-6xl mx-auto p-6 space-y-8 animate-in fade-in slide-in-from-bottom-4 duration-500 pb-20">
            {/* Header */}
            <div className="flex items-center justify-between">
                <div className="flex items-center gap-4">
                    <button onClick={onBack} title="Geri Dön" className="p-3 bg-white dark:bg-white/5 border border-slate-200 dark:border-white/10 rounded-2xl hover:bg-slate-50 dark:hover:bg-white/10 transition-all shadow-sm group">
                        <ArrowLeft className="group-hover:-translate-x-1 transition-transform" />
                    </button>
                    <div>
                        <h1 className="text-2xl font-black text-slate-900 dark:text-white uppercase tracking-tight italic">Robots.txt Hazırlayıcı</h1>
                        <p className="text-slate-500 text-sm font-medium">Büyük arama motorlarına hangi sayfaları tarayacaklarını söyleyin.</p>
                    </div>
                </div>
                <div className="flex gap-2">
                    <button onClick={handleCopy} className="p-3 bg-white dark:bg-white/5 border border-slate-200 dark:border-white/10 rounded-xl text-xs font-black uppercase tracking-widest text-slate-600 dark:text-slate-400 hover:text-blue-500 transition-all">
                        {copied ? <Check size={16} className="text-emerald-500" /> : <Copy size={16} />}
                    </button>
                    <button onClick={downloadFile} className="p-3 bg-slate-900 dark:bg-white text-white dark:text-slate-900 rounded-xl text-xs font-black uppercase tracking-widest hover:scale-105 transition-all shadow-lg active:scale-95 flex items-center gap-2">
                        <Download size={16} /> ROBOTS.TXT İNDİR
                    </button>
                </div>
            </div>

            <div className="grid grid-cols-1 lg:grid-cols-2 gap-8">
                {/* Rule Manager */}
                <div className="space-y-6">
                    <div className="bg-white dark:bg-[#0b101b] border-2 border-slate-100 dark:border-white/5 rounded-[2.5rem] p-8 shadow-sm space-y-6">
                        <div className="space-y-4">
                            <label className="text-[10px] font-black uppercase text-slate-400 tracking-widest ml-1">Sitemap Bağlantısı</label>
                            <input
                                type="text"
                                value={sitemap}
                                onChange={(e) => setSitemap(e.target.value)}
                                placeholder="https://example.com/sitemap.xml"
                                className="w-full bg-slate-50 dark:bg-white/5 border border-slate-200 dark:border-white/10 rounded-xl p-4 text-sm font-mono text-blue-500 focus:outline-none focus:ring-4 focus:ring-blue-500/10 transition-all"
                            />
                        </div>

                        <div className="space-y-4">
                            <div className="flex items-center justify-between px-1">
                                <label className="text-[10px] font-black uppercase text-slate-400 tracking-widest">Bot Kuralları</label>
                                <button onClick={addRule} className="text-[10px] font-black uppercase tracking-widest text-blue-500 flex items-center gap-1 hover:underline">
                                    <Plus size={12} /> Kural Ekle
                                </button>
                            </div>

                            <div className="space-y-3 max-h-[400px] overflow-y-auto pr-2 custom-scrollbar">
                                {rules.map((r) => (
                                    <div key={r.id} className="p-4 bg-slate-50 dark:bg-white/[0.02] border border-slate-100 dark:border-white/5 rounded-2xl relative group">
                                        <button onClick={() => removeRule(r.id)} className="absolute -top-2 -right-2 w-6 h-6 bg-red-500 text-white rounded-full flex items-center justify-center opacity-0 group-hover:opacity-100 transition-all shadow-lg">
                                            <X size={12} />
                                        </button>
                                        <div className="grid grid-cols-1 md:grid-cols-3 gap-3">
                                            <div className="space-y-1">
                                                <span className="text-[9px] font-bold text-slate-400 uppercase">User-agent</span>
                                                <input
                                                    value={r.agent}
                                                    onChange={(e) => updateRule(r.id, { agent: e.target.value })}
                                                    className="w-full bg-white dark:bg-slate-800 border-none rounded-lg p-2 text-xs font-bold focus:ring-2 focus:ring-blue-500/30"
                                                />
                                            </div>
                                            <div className="space-y-1">
                                                <span className="text-[9px] font-bold text-slate-400 uppercase">Durum</span>
                                                <select
                                                    value={r.type}
                                                    onChange={(e) => updateRule(r.id, { type: e.target.value })}
                                                    className="w-full bg-white dark:bg-slate-800 border-none rounded-lg p-2 text-xs font-bold focus:ring-2 focus:ring-blue-500/30 outline-none"
                                                >
                                                    <option value="Allow">Allow</option>
                                                    <option value="Disallow">Disallow</option>
                                                    <option value="Crawl-delay">Crawl-delay</option>
                                                </select>
                                            </div>
                                            <div className="space-y-1">
                                                <span className="text-[9px] font-bold text-slate-400 uppercase">Dizin/Yol</span>
                                                <input
                                                    value={r.path}
                                                    onChange={(e) => updateRule(r.id, { path: e.target.value })}
                                                    className="w-full bg-white dark:bg-slate-800 border-none rounded-lg p-2 text-xs font-bold focus:ring-2 focus:ring-blue-500/30"
                                                />
                                            </div>
                                        </div>
                                    </div>
                                ))}
                            </div>
                        </div>
                    </div>
                </div>

                {/* Live Preview */}
                <div className="space-y-6 flex flex-col">
                    <div className="bg-slate-900 border border-white/5 rounded-[2.5rem] p-8 shadow-xl flex flex-col h-full relative overflow-hidden">
                        <div className="absolute top-0 left-0 p-8 opacity-5">
                            <Shield size={120} />
                        </div>
                        <div className="flex items-center justify-between mb-6 relative z-10">
                            <h3 className="text-white text-lg font-black uppercase tracking-tight flex items-center gap-2">
                                <FileText className="text-blue-500" size={20} /> ROBOTS.TXT
                            </h3>
                            <div className="flex items-center gap-2 px-3 py-1 bg-white/5 rounded-full border border-white/5">
                                <div className="w-2 h-2 rounded-full bg-emerald-500 animate-pulse" />
                                <span className="text-[9px] font-black text-slate-400 uppercase tracking-widest">Canlı Çıktı</span>
                            </div>
                        </div>
                        <div className="flex-1 bg-black/40 border border-white/5 rounded-2xl p-6 overflow-hidden relative z-10">
                            <pre className="text-[12px] font-mono text-emerald-400/80 whitespace-pre-wrap h-[300px] overflow-y-auto custom-scrollbar leading-relaxed">
                                {generateRobots()}
                            </pre>
                        </div>
                    </div>

                    <div className="p-6 bg-amber-500/5 border border-amber-500/20 rounded-[2rem] flex gap-4">
                        <AlertCircle className="text-amber-500 shrink-0" size={20} />
                        <p className="text-[11px] text-amber-600 dark:text-amber-400/80 font-medium leading-relaxed">
                            <strong className="block mb-1">DİKKAT!</strong>
                            Disallow: / kuralı tüm sitenizin arama motorları tarafından taranmasını engeller. Önemli sayfalarınızı yanlışlıkla Disallow etmediğinizden emin olun.
                        </p>
                    </div>
                </div>
            </div>

            {/* Guide */}
            <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
                <div className="p-8 bg-slate-900 border border-white/5 rounded-[2.5rem] shadow-sm">
                    <ShieldCheck className="text-emerald-500 mb-4" size={24} />
                    <h3 className="text-white font-bold mb-2">Güvenlik Kontrolü</h3>
                    <p className="text-xs text-slate-500 leading-relaxed font-medium">Hassas dizinlerinizi (admin, api, logs gibi) Disallow ederek botların bu kısımları boşuna taranmasını ve açık yaratmasını önleyin.</p>
                </div>
                <div className="p-8 bg-blue-600 rounded-[2.5rem] shadow-xl text-white">
                    <RefreshCw className="text-blue-200 mb-4" size={24} />
                    <h3 className="font-bold mb-2 text-white">Crawl Budget</h3>
                    <p className="text-xs text-blue-100 leading-relaxed font-medium">Arama motorlarının sitenizi tarama limitini (Crawl Budget) verimli kullanmak için önemsiz sayfaları engellemek SEO puanınızı artırır.</p>
                </div>
                <div className="p-8 bg-white dark:bg-white/5 border border-slate-100 dark:border-white/5 rounded-[2.5rem] shadow-sm">
                    <Globe className="text-blue-500 mb-4" size={24} />
                    <h3 className="font-bold text-slate-800 dark:text-white mb-2">Evrensel Standart</h3>
                    <p className="text-xs text-slate-500 leading-relaxed font-medium">Robots.txt internetin anayasasıdır. Tüm büyük botlar (Googlebot, Bingbot, Slurp) bu dosyadaki kuralları öncelikle kontrol eder.</p>
                </div>
                {/* Closing the existing grid */}
            </div>

            {/* Hoca Köşesi Academy Section */}
            <div className="mt-12 p-10 bg-indigo-600 rounded-[3rem] text-white shadow-2xl relative overflow-hidden group/academy">
                <div className="absolute top-0 right-0 p-10 opacity-10 group-hover/academy:scale-110 transition-transform">
                    <BookOpen size={150} />
                </div>

                <div className="relative z-10 flex flex-col md:flex-row gap-8 items-start">
                    <div className="p-4 bg-white/10 rounded-3xl backdrop-blur-md border border-white/20">
                        <Sparkles className="w-8 h-8 text-indigo-200" />
                    </div>

                    <div className="space-y-4 max-w-3xl">
                        <h3 className="text-2xl font-black uppercase italic tracking-tight">Hoca Köşesi: Robots.txt Kodun Kapı Görevlisidir</h3>
                        <p className="text-indigo-50 font-bold italic leading-relaxed">
                            "Hocam, robots.txt bir 'yasak tabelası' değil, bir 'nezaket ricası'dır.
                            Google ve diğer saygın arama motorları bu rıcaya uyar ama kötü niyetli botlar (crawler) buna bakmaz bile.
                            Hassas verilerinizi oraya yazıp 'Disallow: /ozel-sifreler' derseniz, tam tersine hırsıza anahtarı nerede sakladığınızı göstermiş olursunuz!
                            Gerçek gizlilik için sunucu taraflı yetkilendirme (Auth) şarttır.
                            Ayrıca <span className="underline decoration-indigo-300">User-agent: *</span> her botu kapsar ama Google için özel kurallar yazmak isterseniz <span className="underline decoration-indigo-300">User-agent: Googlebot</span> olarak ayrı bir blok açmanız gerekir."
                        </p>
                    </div>
                </div>
            </div>
        </div>
    );
};
